language: cpp
sudo: required
dist: trusty
compiler: gcc
before_install:
  - export CXX="g++-4.9"
install:
  - eval "$(gimme 1.6)"
  - make travis-get-deps
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - make CXX=g++-4.9 CC=gcc-4.9
  - cd Exec
  - ./KVEngine --run-tests
after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov -c -d . -o coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system code
  - lcov --remove coverage.info 'Tests/*' --output-file coverage.info # remove tests from coverage
  - lcov --remove coverage.info '/griefly/build/*' --output-file coverage.info # remove gtest and generated code from coverage
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov --repo-token=${COVERALLS_TOKEN} coverage.info # uploads to cov
